### ISSUE TITLE
Task 0

### ISSUE THREAD

**Issue by Antonious-Awad** [Antonious-Awad/printf#5]
# To Do
## Subtask 1 - @GeorgeSamir10 
- [x] Create `main.h` 
- [x] Add prototype to `main.h`
- [x] Initiate `_printf.c`
- [x] implement `_putchar.c` and add it to prototype

## Subtask 2 - @GeorgeSamir10 
- [x] Create `_print_char.c`
- [x] Add prototype to `main.h`
- [x] implement `_print_char.`

## Subtask 3 - @Antonious-Awad 
- [x] Create `_print_string.c`
- [x] Add prototype to `main.h`
- [x] implement `_print_string.`

## Subtask 4 - @Antonious-Awad 
- [x] Create `_print_percent.c`
- [x] Add prototype to `main.h`
- [x] implement `_print_percent.`
